default:
  name: ''
  # global_cfg_layering
development:
  name: developer
  celery:
    broker: 'redis://localhost:6379/1'
    backend: 'redis://localhost:6379/2'
    timezone: "Asia/Shanghai"
    enable_utc: False
  # development_environment_cfg
production:
  name: admin
  # production_environment_cfg